### ISSUE TITLE
Extension prevents `Code actions` with keyboard shortchut `Ctrl + .`

### ISSUE THREAD

**Issue by davidnwaneri** [Rexfordasamoah51/flutter-insider#1]
The default behaviour with the keyboard shortcut `Ctrl + .` brings up code actions on any widget. But with the extension enabled, `code actions` does not show. I'm unsure if this is only in a case when it returns the `No widget found` dialogue at the bottom right of the screen,

To Replicate:
- Create a flutter project, or open existing Flutter project
- With the default project template, try to invoke code actions on any widget with `Ctrl + .`

**Comment by rexthecoder** [comment]
Hello @davidnwaneri , 

`Ctrl + .` is a hotKey for windows, basically, when you highlight any widget, and then use that hotKey, it is supposed to search automatically. 

You can customize that to your choice, this will allow `code actions` to work once again

To Customise that, you can go to extension settings and change windows hotKey to your preferences. 😋

**Comment by davidnwaneri** [comment]
I guess that works.
